name: Build and run on GitHub Actions

on:
  workflow_dispatch:
  schedule:
    - cron: '41 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev

    - name: Configure git
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'tzdbics@users.noreply.github.com'

    - name: Run the build script
      run: ./build.sh

    - name: Archive artifacts if any
      uses: actions/upload-artifact@v4
      with:
        name: tzdbics_artifacts
        path: build/out/
        if-no-files-found: ignore

    - name: Push changes
      run: git push
